# Generated by Django 5.2.4 on 2025-07-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='StackIt', max_length=100)),
                ('site_description', models.TextField(default='A Q&A platform for developers')),
                ('allow_registration', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('max_tags_per_question', models.PositiveIntegerField(default=5)),
                ('min_reputation_to_vote', models.PositiveIntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
